/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: hello24.c                                             *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5793 (22419)                                *
* Character disabled:  0x5793 (22419)                                *
* Character enabled:   0x5783 (22403)                                *
* Save pattern file: C:\Users\ningjianwem\Desktop\1.txt              *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ningjianwem\Desktop\1.txt              *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonthello24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fonthello24_4F60[ 51] = { /* code 4F60 */
  _____X__,_X______,________,
  ____XX__,XX______,________,
  ____X___,X_______,________,
  ____X___,XXXXXXXX,X_______,
  ___X___X,________,X_______,
  __XX__XX,___X___X,X_______,
  __XX__X_,___X___X,________,
  _XXX____,___X____,________,
  XX_X____,X__X__X_,________,
  X__X____,X__X___X,________,
  ___X___X,___X___X,________,
  ___X___X,___X____,X_______,
  ___X__XX,___X____,XX______,
  ___X__X_,___X____,_X______,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonthello24_597D[ 51] = { /* code 597D */
  ___X____,________,________,
  ___X____,XXXXXXXX,X_______,
  ___X____,_______X,X_______,
  __X_____,______XX,________,
  XXXXXXX_,_____XX_,________,
  __X___X_,____XX__,________,
  __X___X_,____X___,________,
  _X____X_,____X___,________,
  _X___XXX,XXXXXXXX,XX______,
  _X___X__,____X___,________,
  _XX__X__,____X___,________,
  ___XXX__,____X___,________,
  ____X___,____X___,________,
  ___X_XX_,____X___,________,
  __X___XX,____X___,________,
  _XX_____,____X___,________,
  X_______,_XXX____,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fonthello24_CharInfo[2] = {
   {  18,  17,   0,   4,  18, acGUI_Fonthello24_4F60 } /* code 4F60 */
  ,{  18,  17,   0,   4,  18, acGUI_Fonthello24_597D } /* code 597D */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonthello24_Prop2 = {
   0x597D /* first character */
  ,0x597D /* last character  */
  ,&GUI_Fonthello24_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fonthello24_Prop1 = {
   0x4F60 /* first character */
  ,0x4F60 /* last character  */
  ,&GUI_Fonthello24_CharInfo[  0] /* address of first character */
  ,&GUI_Fonthello24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonthello24_Prop1}
  ,19 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

